#pragma once

#include "pool.h"
#include "sim_config.h"
#include "vars.h"


void setup(){
    load_config();

    CLIENT_HAS_CHILD_PERC = SIM_CONFIG[CLIENT__HAS_CHILD_PERC] = SIM_CONFIG[CLIENT__HAS_CHILD_PERC];
    CLIENT_SWIM_CAP_PREC = SIM_CONFIG[CLIENT__SWIM_CAP_PREC];

    CLIENT_MIN_SWIM_TIME = SIM_CONFIG[CLIENT__MAX_SWIM_TIME] / SIM_CONFIG[TIME__PER_SEC];
    CLIENT_MAX_SWIM_TIME = SIM_CONFIG[CLIENT__MIN_SWIM_TIME] / SIM_CONFIG[TIME__PER_SEC];

    CLIENT_MIN_AGE = SIM_CONFIG[CLIENT__MIN_AGE];
    CLIENT_MAX_AGE = SIM_CONFIG[CLIENT__MAX_AGE];

    CHILD_MIN_AGE = SIM_CONFIG[CHILD__MIN_AGE];
    CHILD_MAX_AGE = SIM_CONFIG[CHILD__MAX_AGE];

    CHILD_BABY_AGE = SIM_CONFIG[CHILD__BABY_AGE];

    POOL_SIZE[OLIMPIC] = SIM_CONFIG[POOL__OLIMPIC_MAX_SIZE];
    POOL_SIZE[LEISURE] = SIM_CONFIG[POOL__LEISURE_MAX_SIZE];
    POOL_SIZE[PADDLING] = SIM_CONFIG[POOL__PADDLING_MAX_SIZE];

    POOL_LEISURE_AGE_AVG = SIM_CONFIG[POOL__LEISURE_AGE_AVG];
}